### ISSUE TITLE
Enhancement request - make the control points easier to grab with mouse/stylus

### ISSUE THREAD

**Issue by splitn2** [mikemag/snoCAD-X#5]
As suggested by David AKA "the,quass" in this conversation ...... 
http://skibuilders.com/phpBB2/viewtopic.php?t=4779

"My only issue is the pick points are pretty tiny at high res so they are really difficult to drag with the stylus. I could change red and it would sort this I think"

I agree with him they are hard to grab with the mouse and in a tablet he finds it tricky with stylus. Can they be locked on to easier and more visible?

cheers
Rich

**Comment by splitn2** [comment]
As suggested by David AKA "the,quass".

"My only issue is the pick points are pretty tiny at high res so they are really difficult to drag with the stylus. I could change red and it would sort this I think"

I agree with him they are hard to grab with the mouse too I find. Can they be locked on to easier and more visible?

cheers
Rich

**Comment by danielgraf** [comment]
I've never used git before so I thought I'd give this simple one a bash. I've doubled the size of the control handles when activated, increased the activation area, and increased the size of the handles when inactive. @Rich if you're able to compile the project and take a look, let me know if it's what you had in mind and close or comment again as you see fit. I'm gonna get us to use git at work, this was much more pleasant than SVN !

**Comment by splitn2** [comment]
haha @danielgraf I'll leave compile for the experts mate, I once used an assembler compiler for Intel 8031 but my code was a mess honestly a total mess! So letting me loose on this compiling is like a machine gun in a childs hands - dangerous, I'll leave that to @mikemag to do the releases!!!!!

**Comment by mikemag** [comment]
Released: https://github.com/mikemag/snoCAD-X/releases

Personally, I found the control points much easier to grab, and not too big. Nicely done.
